name: plant_app_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.4
  get: ^4.6.6
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.3+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: kalam
      fonts:
        - asset: assets/fonts/Kalam-Regular.ttf


        
  
