name: school_management_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_database: ^11.0.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  #sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
